before_install:
- wget https://github.com/CynepHy6/ap/releases/download/0.9.15/ap-ubuntu64
install:
- chmod +x ./ap-ubuntu64
script: 
- for D in src/*; do ./ap-ubuntu64 ${D}/;  done
- if [ -d "ecosystem_apps" ]; then cd ecosystem_apps; for D in *; do if [ -d ${D} ]; then ../ap-ubuntu64 ${D}/; fi; done; cd ..; fi;
- if [ -d "platform_apps" ]; then cd platform_apps; for D in *; do if [ -d ${D} ]; then ../ap-ubuntu64 ${D}/; fi; done; cd ..; fi; 
after_success:
- git checkout ${TRAVIS_BRANCH}
- git config --global user.email "builds@travis-ci.com" 
- git config --global user.name "Travis CI"
- git remote add origin-master https://${GITHUB_TOKEN}@github.com/GenesisKernel/apps > /dev/null 2>&1
- git add ./*.json
- if [ -d "ecosystem_apps" ]; then git add ecosystem_apps/*.json; fi
- if [ -d "platform_apps" ]; then git add platform_apps/*.json; fi
- git commit --message "Autobuild N.$TRAVIS_BUILD_NUMBER [ci skip]"
- git push origin-master